apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - github.com/argoproj/argocd-example-apps/kustomize-guestbook/?ref=6bed858de32a0e876ec49dad1a2e3c5840d3fb07
