apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  # v1.5.5
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=0fdef4861e12026e133224f7c9413072340e2983
  - argo-cd-service-monitor.yaml
  # Applications to deploy
  - applications/example-book.yaml
  - applications/prometheus-operator.yaml
patches:
  - argo-cd-repo-server-ksops-patch.yaml
  - argo-cd-allow-alpha-plugins-patch.yaml
  - argo-cd-import-pgp-key.yaml
  - argo-cd-repository-credentials-patch.yaml
images:
  - name: argoproj/argocd:v1.5.5
    digest: sha256:b83f7dafd3d7c21bbaea15d5ce13e699433d7736f5d441e752033663d4fa6e6c
  - name: quay.io/dexidp/dex:v2.22.0
    digest: sha256:01e996b4b60edcc5cc042227c6965dd63ba68764c25d86b481b0d65f6e4da308
  - name: redis:5.0.3
#     digest: sha256:0f88f9be58390a5d67c1a7dbcd08691e059fea2dba7cef42dfc41fab513f43bb
  - name: viaductoss/ksops:v2.1.0
    digest: sha256:2f21264a483056102523be37431ba7971d991f2aa872c725f22fa074005b1d26
generators:
  - secret-generator.yaml
