apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  # v1.5.4
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=36bade7a2d7b69d1c0b0c4d41191f792a847d61c
  # Applications to deploy
  - applications/example-book.yaml
  - applications/prometheus-operator.yaml
patches:
  - argo-cd-repo-server-ksops-patch.yaml
  - argo-cd-allow-alpha-plugins-patch.yaml
  - argo-cd-import-pgp-key.yaml
  - argo-cd-repository-credentials-patch.yaml
images:
  - name: argoproj/argocd:v1.5.4
    digest: sha256:9b55703f06eff3b30320109f372fc15092fb07b9e0c1e2ee5c71fd7ff7a14b66
  - name: quay.io/dexidp/dex:v2.22.0
    digest: sha256:01e996b4b60edcc5cc042227c6965dd63ba68764c25d86b481b0d65f6e4da308
  - name: redis:5.0.3
#     digest: sha256:0f88f9be58390a5d67c1a7dbcd08691e059fea2dba7cef42dfc41fab513f43bb
  - name: viaductoss/ksops:v2.1.0
    digest: sha256:2f21264a483056102523be37431ba7971d991f2aa872c725f22fa074005b1d26
generators:
  - secret-generator.yaml
