apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
spec:
  project: default
  source:
    path: prometheus-operator/
    repoURL: git@github.com:james-callahan/example-gitops.git
    targetRevision: HEAD
  destination:
    namespace: prometheus-operator
    server: https://kubernetes.default.svc
